#ifndef RASPICOMMON_H
#define RASPICOMMON_H

/* Drive modes for the car:
 * - manual: steer direct from user interface
 * - auto_nominal: use semi-auto or auto instructions to drive
 * - auto_critical: same as above, but in an intersection or when image
 *   processing gave unreliable data. */
namespace drive_mode {
    enum DriveMode {manual, auto_nominal, auto_critical};
}

namespace instruction {
    enum InstructionNumber {
        left = 0, forward = 1, right = 2, stop = 3
    };
}

/* The simple instructions got from user interface in semi-auto mode
 * and generated from drive missions in auto mode. */
typedef struct DriveInstruction {
    enum instruction::InstructionNumber number;
    std::string id;
} drive_instruction_t;

/* The references generated by ControlModule */
typedef struct ReferenceStruct {
    int speed;
    int angle;
    enum drive_mode::DriveMode drive_mode;
} reference_t;

/* The data produced by ImageProcessingModule */
typedef struct image_proc_t {
    bool status_code = 0;
    int lateral_position = 0;
    int stop_distance = 0;
    int angle_left = 0;
    int angle_right = 0;
} image_proc_t;

/* The data produced by sensor module */
typedef struct sensor_data_type {
    int obstacle_distance = 0;
    int driving_distance = 0;
    int speed = 0;
} sensor_data_t;

#endif  // RASPICOMMON_H
