#ifndef RASPICOMMON_H
#define RASPICOMMON_H

/* Drive modes for the car:
 * - manual: steer direct from user interface
 * - auto_nominal: use semi-auto or auto instructions to drive
 * - auto_critical: same as above, but in an intersection or when image
 *   processing gave unreliable data. */
namespace drive_mode {
    enum DriveMode {manual, auto_nominal, auto_critical};
}

/* The references generated by ControlModule */
typedef struct ReferenceStruct {
    int speed;
    int angle;
    enum drive_mode::DriveMode drive_mode;
} reference_t;

#endif  // RASPICOMMON_H
